#!/usr/bin/env python3
"""
Step 5: Hard Negative and Collision Forensics
Quantifies collisions in the training dataset:
1. Identical/normalized name collisions across different entities
2. Address collisions (multi-tenant buildings, malls, tech parks)
3. Postal/PIN code cardinality and candidate explosion risk
4. Analysis of false candidate pairs generated by simplistic blocking
"""

import os
import json
import re
from collections import Counter
import polars as pl
import numpy as np

def clean_str(s):
    if s is None:
        return ""
    return re.sub(r"\s+", " ", re.sub(r"[^\w\s]", " ", s.lower())).strip()

def extract_pin_codes(s):
    if not s:
        return set()
    # Matches 6-digit Indian PIN or 5-digit US ZIP
    return set(re.findall(r"\b\d{5,6}\b", s))

def main():
    print("Loading datasets for Collision Forensics...")
    s1_df = pl.read_csv("dataset/raw/train/train_source1.tsv", separator="\t")
    s2_df = pl.read_csv("dataset/raw/train/train_source2.tsv", separator="\t")
    s3_df = pl.read_csv("dataset/raw/train/train_source3.tsv", separator="\t")
    gt_df = pl.read_csv("dataset/raw/train/train_ground_truth.tsv", separator="\t")

    print("Building true match lookup...")
    gt_exploded = (
        gt_df.filter(pl.col("matched_entity_ids").is_not_null() & (pl.col("matched_entity_ids") != ""))
        .with_columns(pl.col("matched_entity_ids").str.split(","))
        .explode("matched_entity_ids")
        .with_columns(pl.col("matched_entity_ids").str.strip_chars())
    )
    true_pairs = set(zip(gt_exploded["source1_entity_id"], gt_exploded["matched_entity_ids"]))
    print(f"True positive pairs in GT: {len(true_pairs):,}")

    # 1. Source 1 Internal Name Collisions
    print("Analyzing Source 1 Name Collisions...")
    s1_names = s1_df["business_name"].fill_null("").to_list()
    s1_ids = s1_df["entity_id"].to_list()
    
    clean_s1_names = [clean_str(n) for n in s1_names]
    name_counts = Counter(n for n in clean_s1_names if n)
    
    multi_entity_names = {k: v for k, v in name_counts.items() if v > 1}
    top_colliding_names = sorted(multi_entity_names.items(), key=lambda x: x[1], reverse=True)[:30]
    
    total_s1 = len(s1_df)
    entities_with_shared_names = sum(v for v in multi_entity_names.values())
    
    print(f"S1 unique clean names: {len(name_counts):,} out of {total_s1:,}")
    print(f"Clean names appearing >1 time: {len(multi_entity_names):,} (covering {entities_with_shared_names:,} entities, {entities_with_shared_names/total_s1*100:.2f}%)")

    # 2. Address Collisions in S1
    print("Analyzing Source 1 Address Collisions...")
    s1_addrs = s1_df["business_address"].fill_null("").to_list()
    clean_s1_addrs = [clean_str(a) for a in s1_addrs]
    addr_counts = Counter(a for a in clean_s1_addrs if a)
    multi_entity_addrs = {k: v for k, v in addr_counts.items() if v > 1}
    top_colliding_addrs = sorted(multi_entity_addrs.items(), key=lambda x: x[1], reverse=True)[:20]
    entities_with_shared_addrs = sum(v for v in multi_entity_addrs.values())

    print(f"S1 unique clean addresses: {len(addr_counts):,} out of {total_s1:,}")
    print(f"Clean addresses appearing >1 time: {len(multi_entity_addrs):,} (covering {entities_with_shared_addrs:,} entities, {entities_with_shared_addrs/total_s1*100:.2f}%)")

    # 3. Cross-source Name Collision / Blocking Explosion Analysis (S1 vs S2)
    print("Analyzing S1 vs S2 Name-based candidate collisions...")
    # Sample 50,000 S1 entities to evaluate candidate explosion if blocking by exact clean name
    sample_s1 = s1_df.sample(n=min(50000, len(s1_df)), seed=42)
    s1_sample_dict = {row[0]: clean_str(row[1]) for row in sample_s1.select(["entity_id", "business_name"]).iter_rows()}
    
    s2_name_index = {}
    for eid, bname in s2_df.select(["entity_id", "business_name"]).iter_rows():
        cn = clean_str(bname)
        if cn:
            if cn not in s2_name_index:
                s2_name_index[cn] = []
            s2_name_index[cn].append(eid)
            
    # Measure precision of exact clean name matching
    true_candidates = 0
    total_candidates_generated = 0
    s1_with_candidates = 0
    candidate_list_lengths = []
    
    for s1_id, cn in s1_sample_dict.items():
        if cn in s2_name_index:
            s1_with_candidates += 1
            s2_cands = s2_name_index[cn]
            n_cands = len(s2_cands)
            candidate_list_lengths.append(n_cands)
            total_candidates_generated += n_cands
            for s2_id in s2_cands:
                if (s1_id, s2_id) in true_pairs:
                    true_candidates += 1

    candidate_precision = (true_candidates / total_candidates_generated) if total_candidates_generated else 0
    print(f"Exact Clean Name Matching across sample of {len(s1_sample_dict):,} S1 entities against S2:")
    print(f"  Total candidate pairs generated: {total_candidates_generated:,}")
    print(f"  True positive pairs among candidates: {true_candidates:,}")
    print(f"  Candidate precision (True Positives / Total Candidates): {candidate_precision*100:.2f}%")
    print(f"  False Positive Rate in exact-name candidates: {(1 - candidate_precision)*100:.2f}%")

    results = {
        "s1_name_collisions": {
            "total_s1_records": total_s1,
            "unique_clean_names": len(name_counts),
            "clean_names_with_multiple_entities": len(multi_entity_names),
            "entities_affected_by_name_collision": entities_with_shared_names,
            "pct_entities_sharing_name": round(entities_with_shared_names / total_s1 * 100, 2),
            "top_30_colliding_names": [{"name": k, "entity_count": v} for k, v in top_colliding_names]
        },
        "s1_address_collisions": {
            "total_s1_records": total_s1,
            "unique_clean_addrs": len(addr_counts),
            "clean_addrs_with_multiple_entities": len(multi_entity_addrs),
            "entities_affected_by_addr_collision": entities_with_shared_addrs,
            "pct_entities_sharing_addr": round(entities_with_shared_addrs / total_s1 * 100, 2),
            "top_20_colliding_addrs": [{"address": k, "entity_count": v} for k, v in top_colliding_addrs]
        },
        "exact_name_blocking_simulation_s1_s2": {
            "sample_s1_size": len(s1_sample_dict),
            "s1_with_at_least_one_candidate": s1_with_candidates,
            "total_candidates_generated": total_candidates_generated,
            "true_positive_candidates": true_candidates,
            "candidate_precision_pct": round(candidate_precision * 100, 2),
            "false_candidate_rate_pct": round((1 - candidate_precision) * 100, 2),
            "avg_candidates_when_matched": round(np.mean(candidate_list_lengths), 2) if candidate_list_lengths else 0,
            "max_candidates_for_single_s1": int(np.max(candidate_list_lengths)) if candidate_list_lengths else 0
        }
    }

    out_path = "research_scripts/05_hard_negative_results.json"
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2)
    print(f"\nHard negative and collision forensics saved to {out_path}")

if __name__ == "__main__":
    main()
